database:
  driver: postgres
  host: localhost
  port: 5432
  user: lang
  password: password
  dbname: urldb
  ssl_mode: disable
  max_idle_conns: 5
  max_open_conns: 5

redis:
  address: localhost:6379
  password:
  db: 0
  url_duration: 1h
  email_code_duration: 2m
  sync_view_duration: 2h

email:
  password:
  mymail:
  host_address:
  host_port:
  subject:
  test_mail:

server:
  addr: ":8080"
  read_timeout: 5s
  write_timeout: 5s

app:
  base_url: "http://localhost:8080"
  default_duration: 10h
  cleanup_interval: 2h

shortcode:
  length: 6

logger:
  level: info

jwt:
  secret: "mycompletedsecret"
  duration: 24h
